#!/bin/bash
# examples/worktree-hooks.express.sh
# Example hooks for an Express/Node.js project with PostgreSQL.
# Copy to .worktree/hooks.sh and customize for your project.

# --- Configuration ---
PG_USER="${PG_USER:-postgres}"
PG_PASSWORD="${PG_PASSWORD:-postgres}"
PG_HOST="${PG_HOST:-localhost}"
APP_NAME="${APP_NAME:-myapp}"

# --- Hook implementations ---

wt_hook_validate_prereqs() {
    echo "Checking prerequisites..."

    if ! command -v node &>/dev/null; then
        echo "Error: node not found. Install Node.js."
        exit 1
    fi

    if ! command -v psql &>/dev/null; then
        echo "Error: psql not found. Install PostgreSQL client."
        exit 1
    fi

    if ! PGPASSWORD="$PG_PASSWORD" psql -U "$PG_USER" -h "$PG_HOST" -c "SELECT 1" postgres &>/dev/null; then
        echo "Error: Cannot connect to PostgreSQL as $PG_USER"
        exit 1
    fi

    # Check for package manager
    if ! command -v npm &>/dev/null; then
        echo "Error: npm not found."
        exit 1
    fi

    echo "Prerequisites OK"
}

wt_hook_create_databases() {
    local wt_id="$1"
    local dev_db="${APP_NAME}_dev_wt${wt_id}"
    local test_db="${APP_NAME}_test_wt${wt_id}"

    echo "  Creating PostgreSQL database: $dev_db" >&2
    PGPASSWORD="$PG_PASSWORD" createdb -U "$PG_USER" -h "$PG_HOST" "$dev_db"

    echo "  Creating PostgreSQL database: $test_db" >&2
    PGPASSWORD="$PG_PASSWORD" createdb -U "$PG_USER" -h "$PG_HOST" "$test_db"

    echo "[\"$dev_db\", \"$test_db\"]"
}

wt_hook_generate_env() {
    local wt_path="$1"
    local wt_id="$2"
    local ports_json="$3"

    local server_port
    server_port=$(echo "$ports_json" | jq -r '.server')

    local dev_db="${APP_NAME}_dev_wt${wt_id}"
    local test_db="${APP_NAME}_test_wt${wt_id}"

    cat > "$wt_path/.env" << EOF
# Worktree-specific environment (ID: $wt_id)
# Generated by worktree hooks on $(date)

PORT=$server_port
DATABASE_URL=postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}/${dev_db}
TEST_DATABASE_URL=postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}/${test_db}
NODE_ENV=development
SESSION_SECRET=$(openssl rand -hex 32)
EOF

    echo "  Generated .env" >&2
}

wt_hook_install_deps() {
    local wt_path="$1"

    cd "$wt_path"
    if [ -f "yarn.lock" ]; then
        yarn install
    elif [ -f "pnpm-lock.yaml" ]; then
        pnpm install
    else
        npm install
    fi
    cd - >/dev/null
}

wt_hook_post_setup() {
    local wt_path="$1"
    local wt_id="$2"

    cd "$wt_path"

    # Source env
    set -a
    # shellcheck source=/dev/null
    source .env
    set +a

    # Run migrations (common patterns)
    if [ -f "node_modules/.bin/knex" ]; then
        npx knex migrate:latest
        echo "Running seeds..."
        npx knex seed:run 2>/dev/null || true
    elif [ -f "node_modules/.bin/prisma" ]; then
        npx prisma migrate deploy
    elif [ -f "node_modules/.bin/sequelize" ]; then
        npx sequelize-cli db:migrate
        echo "Running seeds..."
        npx sequelize-cli db:seed:all 2>/dev/null || true
    fi

    cd - >/dev/null
}

wt_hook_pre_cleanup() {
    local wt_path="$1"
    # Kill any running node server
    local pid_file="$wt_path/.server.pid"
    if [ -f "$pid_file" ]; then
        kill "$(cat "$pid_file")" 2>/dev/null || true
    fi
}

wt_hook_drop_databases() {
    local wt_id="$1"
    local databases_json="$2"

    echo "$databases_json" | jq -r '.[]' | while read -r db; do
        if PGPASSWORD="$PG_PASSWORD" psql -U "$PG_USER" -h "$PG_HOST" -lqt 2>/dev/null | cut -d \| -f 1 | grep -qw "$db"; then
            echo "  Dropping PostgreSQL database: $db"
            PGPASSWORD="$PG_PASSWORD" dropdb -U "$PG_USER" -h "$PG_HOST" "$db"
        else
            echo "  PostgreSQL database '$db' not found (skipping)"
        fi
    done
}
