#!/bin/bash
# examples/worktree-hooks.phoenix.sh
# Example hooks for a Phoenix/Elixir project with PostgreSQL.
# Copy to .worktree/hooks.sh and customize for your project.

# --- Configuration ---
# Database user/password (customize for your project)
PG_USER="${PG_USER:-postgres}"
PG_PASSWORD="${PG_PASSWORD:-postgres}"
PG_HOST="${PG_HOST:-localhost}"
APP_NAME="${APP_NAME:-myapp}"

# --- Hook implementations ---

wt_hook_validate_prereqs() {
    echo "Checking prerequisites..."

    if ! command -v mix &>/dev/null; then
        echo "Error: mix not found. Install Elixir first."
        exit 1
    fi

    if ! command -v psql &>/dev/null; then
        echo "Error: psql not found. Install PostgreSQL client."
        exit 1
    fi

    if ! PGPASSWORD="$PG_PASSWORD" psql -U "$PG_USER" -h "$PG_HOST" -c "SELECT 1" postgres &>/dev/null; then
        echo "Error: Cannot connect to PostgreSQL as $PG_USER"
        exit 1
    fi

    echo "Prerequisites OK"
}

wt_hook_create_databases() {
    local wt_id="$1"
    local dev_db="${APP_NAME}_dev_wt${wt_id}"
    local test_db="${APP_NAME}_test_wt${wt_id}"

    echo "  Creating PostgreSQL database: $dev_db" >&2
    PGPASSWORD="$PG_PASSWORD" createdb -U "$PG_USER" -h "$PG_HOST" "$dev_db"

    echo "  Creating PostgreSQL database: $test_db" >&2
    PGPASSWORD="$PG_PASSWORD" createdb -U "$PG_USER" -h "$PG_HOST" "$test_db"

    # Return JSON array of created databases (stdout)
    echo "[\"$dev_db\", \"$test_db\"]"
}

wt_hook_generate_env() {
    local wt_path="$1"
    local wt_id="$2"
    local ports_json="$3"

    local phx_port
    phx_port=$(echo "$ports_json" | jq -r '.server')

    local dev_db="${APP_NAME}_dev_wt${wt_id}"
    local test_db="${APP_NAME}_test_wt${wt_id}"

    cat > "$wt_path/.env.local" << EOF
# Worktree-specific environment (ID: $wt_id)
# Generated by worktree hooks on $(date)

export PHX_PORT=$phx_port
export DATABASE_URL=ecto://${PG_USER}:${PG_PASSWORD}@${PG_HOST}/${dev_db}
export TEST_DATABASE_URL=ecto://${PG_USER}:${PG_PASSWORD}@${PG_HOST}/${test_db}
export SECRET_KEY_BASE=$(mix phx.gen.secret 2>/dev/null || openssl rand -hex 64)
EOF

    echo "  Generated .env.local" >&2
}

wt_hook_install_deps() {
    local wt_path="$1"

    cd "$wt_path"
    mix deps.get
    cd - >/dev/null
}

wt_hook_post_setup() {
    local wt_path="$1"
    local wt_id="$2"

    cd "$wt_path"
    source .env.local
    mix ecto.migrate

    if [ -f "priv/repo/seeds.exs" ]; then
        echo "Running seeds..."
        mix run priv/repo/seeds.exs
    fi
    cd - >/dev/null
}

wt_hook_pre_cleanup() {
    local wt_path="$1"
    # Kill any running Phoenix server in this worktree
    local pid_file="$wt_path/tmp/pids/server.pid"
    if [ -f "$pid_file" ]; then
        kill "$(cat "$pid_file")" 2>/dev/null || true
    fi
}

wt_hook_drop_databases() {
    local wt_id="$1"
    local databases_json="$2"

    echo "$databases_json" | jq -r '.[]' | while read -r db; do
        if PGPASSWORD="$PG_PASSWORD" psql -U "$PG_USER" -h "$PG_HOST" -lqt 2>/dev/null | cut -d \| -f 1 | grep -qw "$db"; then
            echo "  Dropping PostgreSQL database: $db"
            PGPASSWORD="$PG_PASSWORD" dropdb -U "$PG_USER" -h "$PG_HOST" "$db"
        else
            echo "  PostgreSQL database '$db' not found (skipping)"
        fi
    done
}
