#!/bin/bash
# examples/worktree-hooks.rails.sh
# Example hooks for a Ruby on Rails project with PostgreSQL.
# Copy to .worktree/hooks.sh and customize for your project.

# --- Configuration ---
PG_USER="${PG_USER:-postgres}"
PG_PASSWORD="${PG_PASSWORD:-postgres}"
PG_HOST="${PG_HOST:-localhost}"
APP_NAME="${APP_NAME:-myapp}"

# --- Hook implementations ---

wt_hook_validate_prereqs() {
    echo "Checking prerequisites..."

    if ! command -v ruby &>/dev/null; then
        echo "Error: ruby not found."
        return 1
    fi

    if ! command -v bundle &>/dev/null; then
        echo "Error: bundler not found. Run: gem install bundler"
        return 1
    fi

    if ! command -v psql &>/dev/null; then
        echo "Error: psql not found. Install PostgreSQL client."
        return 1
    fi

    if ! PGPASSWORD="$PG_PASSWORD" psql -U "$PG_USER" -h "$PG_HOST" -c "SELECT 1" postgres &>/dev/null; then
        echo "Error: Cannot connect to PostgreSQL as $PG_USER"
        return 1
    fi

    echo "Prerequisites OK"
}

wt_hook_create_databases() {
    local wt_id="$1"
    local dev_db="${APP_NAME}_dev_wt${wt_id}"
    local test_db="${APP_NAME}_test_wt${wt_id}"

    echo "  Creating PostgreSQL database: $dev_db" >&2
    PGPASSWORD="$PG_PASSWORD" createdb -U "$PG_USER" -h "$PG_HOST" "$dev_db"

    echo "  Creating PostgreSQL database: $test_db" >&2
    PGPASSWORD="$PG_PASSWORD" createdb -U "$PG_USER" -h "$PG_HOST" "$test_db"

    echo "[\"$dev_db\", \"$test_db\"]"
}

wt_hook_generate_env() {
    local wt_path="$1"
    local wt_id="$2"
    local ports_json="$3"

    local server_port
    server_port=$(echo "$ports_json" | jq -r '.server')

    local dev_db="${APP_NAME}_dev_wt${wt_id}"
    local test_db="${APP_NAME}_test_wt${wt_id}"

    cat > "$wt_path/.env" << EOF
# Worktree-specific environment (ID: $wt_id)
# Generated by worktree hooks on $(date)

PORT=$server_port
DATABASE_URL=postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}/${dev_db}
TEST_DATABASE_URL=postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}/${test_db}
RAILS_ENV=development
SECRET_KEY_BASE=$(openssl rand -hex 64)
EOF

    echo "  Generated .env" >&2
}

wt_hook_install_deps() {
    local wt_path="$1"

    cd "$wt_path"
    bundle install
    if [ -f "yarn.lock" ]; then
        yarn install
    elif [ -f "package-lock.json" ]; then
        npm install
    fi
    cd - >/dev/null
}

wt_hook_post_setup() {
    local wt_path="$1"
    local wt_id="$2"

    cd "$wt_path"
    # Source env for database URL
    set -a
    # shellcheck source=/dev/null
    source .env
    set +a

    bin/rails db:migrate

    if [ -f "db/seeds.rb" ]; then
        echo "Running seeds..."
        bin/rails db:seed
    fi
    cd - >/dev/null
}

wt_hook_pre_cleanup() {
    local wt_path="$1"
    local pid_file="$wt_path/tmp/pids/server.pid"
    if [ -f "$pid_file" ]; then
        kill "$(cat "$pid_file")" 2>/dev/null || true
    fi
}

wt_hook_drop_databases() {
    local wt_id="$1"
    local databases_json="$2"

    echo "$databases_json" | jq -r '.[]' | while read -r db; do
        if PGPASSWORD="$PG_PASSWORD" psql -U "$PG_USER" -h "$PG_HOST" -lqt 2>/dev/null | cut -d \| -f 1 | grep -qw "$db"; then
            echo "  Dropping PostgreSQL database: $db"
            PGPASSWORD="$PG_PASSWORD" dropdb -U "$PG_USER" -h "$PG_HOST" "$db"
        else
            echo "  PostgreSQL database '$db' not found (skipping)"
        fi
    done
}
